version: "3"

services:
  sleek-airflow:
    image: veritas-airflow:latest

    # Install psycopg2-binary into the container by extending the image
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./airflow:/opt/airflow

    ports:
      - "8080:8080"

    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth" # Addressing the FutureWarning about auth_backends

    command: airflow standalone

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
